AWSTemplateFormatVersion: 2010-09-09
Description: 
    Template for lambdas to pull data
    

Resources:
    LambdaJSONImporter: 
        Type: AWS::Lambda::Function
        Properties: 
            MemorySize: 3008
            Handler: "com.cgi.liikennevirasto.jalonne.nouto.LambdaFunctionHandler"
            Role: 
                Fn::ImportValue: !Sub "${JalonenMainStackName}-LambdaPullerExecutionRole"
            Code: 
                S3Bucket: !Ref S3BucketforImporter 
                S3Key: !Ref ImporterLocation 
            Runtime: "java8"
            Timeout: "300"
            TracingConfig:
                Mode: "Active"
            VpcConfig:
                SecurityGroupIds: 
                    - Fn::ImportValue: !Sub "${JalonenMainStackName}-PullerLambdaSecurityGroup"                    #- Fn::ImportValue: !Sub "${JalonenMainStackName}-DBWriterLambdaSecurityGroup" #lisataan manuaalisesti kunnes main-stack luotu uudelleen
                SubnetIds:
                 - Fn::ImportValue: !Sub "${JalonenMainStackName}-PrivateSubnet1"
                 - Fn::ImportValue: !Sub "${JalonenMainStackName}-PrivateSubnet2"
            Environment:
                Variables:
                    dbUrl: !Ref dbUrl
                    dbUser: !Ref dbUser
                    dbPassword: !Ref dbPassword
                    datasource: !Ref  datasource
                    Maintainer: "roudconsulting"
                    Cregion: !Ref "AWS::Region"

Parameters:
    JalonenMainStackName:
        Type: String
        Description: Jalonen main Stack name
        Default: "JalonneMain"

    S3BucketforImporter:
        Type: String
        Description: Which S3 bucket contains Lambda function for importer
        Default: "livijalonnelambdadev"

    ImporterLocation:
        Type: String
        Description: Path to json fetcher and splitter in S3
        Default: "jalonnejsonsplitter-0.0.0.jar"

    datasource:
        Type: String
        Description: source meta url
        Default: "testi"
        
    dbUrl:
        Type: String
        Description: jalonne kuvadata db
        Default: "jdbc:postgresql://ja26l0cdmtgvsr.ceetf0cw6ryo.eu-central-1.rds.amazonaws.com:3306/kuvatieto"
   
    dbUser:
        Type: String
        Description: jalonne db user
        Default: "user"
      
    dbPassword:
        Type: String
        Description: jalonne db password
        Default: "password"

    s3BucketJobs:
       Type: String
       Description: S3 bucket for jalonnejobs
       Default: "jalonnejobbucketdev"
       
    s3BucketImages:
       Type: String
       Description: S3 bucket for jalonnejobs
       Default: "jalonnekuvat"